---
name: matcher-database

channels:
  - conda-forge
  - main
  - nodefaults

dependencies:
  - python == 3.9.2
  - psycopg2 == 2.9.3
  - numpy == 1.22.2
  - scipy == 1.8.0
  - ujson == 5.1.0
  - pip == 22.0.3
  - pip:
      - rdkit-pypi == 2021.3.5
